name: twind
repository: https://github.com/shreyassanthu77/twind

packages:
  - packages/*

scripts:
  analyze:
    exec: flutter analyze
    description: Run Dart analyzer in all packages

  test:
    exec: flutter test
    description: Run tests in all packages
    
  get:
    exec: flutter pub get
    description: Get dependencies for all packages

  format:
    exec: dart format lib test
    description: Format all Dart code

  format:check:
    exec: dart format --set-exit-if-changed lib test
    description: Check Dart code formatting

  clean:
    exec: flutter clean
    description: Clean all packages
