targets:
  $default:
    sources:
      - lib/**
      - test/**
      - example/**
      - $package$
      - pubspec.yaml
    builders:
      twind_generator|tw:
        generate_for:
          - lib/**.dart
          - test/**.dart
          - example/**.dart
