builders:
  tw:
    import: "package:twind_generator/twind_generator.dart"
    builder_factories: ["twindBuilder"]
    build_extensions: {".dart": [".twind.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
